# This compose file is used to simplify local development. For deploying to kubernetes
# please see the examples in the base/ directory.
version: "3.9"
services:
  rabbit:
    image: rabbitmq:3-management
    hostname: rmq
    container_name: fk-rabbit-server
    ports:
      # management server
      - "15672:15672"
      # ?
      - "5672:5672"
  handler:
    container_name: fk-event-handler
    build:
      context: event-handler
    environment:
      FK_BROKER_ADDRESS: rabbit
      FK_TOKEN: changeme
      FK_GITHUB_SECRET: changeme
      PORT: 8080
    ports:
      - "8000:8080"
  gitlab-parser:
    container_name: fk-gitlab-parser
    build:
      context: workers/gitlab-parser
    environment:
      FK_BROKER_ADDRESS: rabbit
      FK_DB_HOST: db
      FK_DB_PW: fourkeys
      FK_DB_USER: fourkeys
    depends_on:
      - rabbit
      - pg
    #volumes: # uncomment to test changes in shared
    #  - ./shared:/app/shared
  github-parser:
    container_name: fk-github-parser
    build:
      context: workers/github-parser
    environment:
      FK_BROKER_ADDRESS: rabbit
      FK_DB_HOST: pg
      FK_DB_PW: fourkeys
      FK_DB_USER: fourkeys
    depends_on:
      - rabbit
      - pg
    #volumes: # uncomment to test changes in shared
    #  - ./shared:/app/shared
  grafana:
    container_name: fk-grafana
    build:
      context: dashboard
    environment:
      FK_DB_USER: fourkeys
      FK_DB_PASSWORD: fourkeys
    ports:
      - "3000:3000"
  pg:
    image: postgres
    container_name: fk-pg
    environment:
      POSTGRES_PASSWORD: fourkeys
      POSTGRES_USER: fourkeys
      POSTGRES_DB: fourkeys
    volumes:
      - ./data-generator/tools/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
