{
 "title": "Four Keys",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Lead Time for Changes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\n    day::DATE as time,\n    COALESCE(AVG(time_diff)/60, 0) AS median_lead_time_for_changes\nFROM (\n    SELECT\n        c.time_created::DATE AS day,\n        d.deploy_id,\n        CASE\n            WHEN EXTRACT(EPOCH FROM (d.time_created - c.time_created))/60 > 0 THEN \n                EXTRACT(EPOCH FROM (d.time_created - c.time_created))/60\n            ELSE \n                NULL\n        END AS time_diff,\n        ROW_NUMBER() OVER(PARTITION BY c.time_created::DATE ORDER BY EXTRACT(EPOCH FROM (d.time_created - c.time_created))/60) AS rn_asc,\n        ROW_NUMBER() OVER(PARTITION BY c.time_created::DATE ORDER BY EXTRACT(EPOCH FROM (d.time_created - c.time_created))/60 DESC) AS rn_desc,\n        COUNT(*) OVER(PARTITION BY c.time_created::DATE) AS cnt\n    FROM changes c\n    JOIN deployments d ON c.change_id = d.main_commit\n) AS subquery\nWHERE rn_asc BETWEEN cnt/2 AND cnt/2 + 1 OR rn_desc BETWEEN cnt/2 AND cnt/2 + 1\nGROUP BY day\nORDER BY day;"
    }
   ]
  },
  {
   "title": "Lead Time to Change Bucket",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "WITH diffs AS (\n    SELECT\n        EXTRACT(EPOCH FROM (d.time_created - c.time_created))/60 AS diff_minutes,\n        ROW_NUMBER() OVER(ORDER BY EXTRACT(EPOCH FROM (d.time_created - c.time_created))/60) AS row_num,\n        COUNT(*) OVER() AS total_count\n    FROM deployments d\n    LEFT JOIN changes c ON d.main_commit = c.change_id\n    WHERE d.time_created > CURRENT_DATE - INTERVAL '3 MONTH'\n    ORDER BY diff_minutes\n)\n\nSELECT \n    CASE\n        WHEN median_time_to_change < 24 * 60 THEN 'One day'\n        WHEN median_time_to_change < 168 * 60 THEN 'One week'\n        WHEN median_time_to_change < 730 * 60 THEN 'One month'\n        WHEN median_time_to_change < 730 * 6 * 60 THEN 'Six months'\n        ELSE 'One year'\n    END AS lead_time_to_change\nFROM (\n    SELECT\n        COALESCE(AVG(diff_minutes), 0) AS median_time_to_change\n    FROM diffs\n    WHERE row_num BETWEEN FLOOR((total_count+1)::NUMERIC/2) AND CEIL((total_count+1)::NUMERIC/2)\n) AS subquery;\n"
    }
   ]
  },
  {
   "title": "Daily Deployments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\nDATE(time_created) AS time,\nCOUNT(DISTINCT deploy_id) AS deployments\nFROM deployments\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "WITH RECURSIVE last_three_months AS (\n    SELECT CURRENT_DATE - INTERVAL '3 MONTH' AS day\n    UNION ALL\n    SELECT day + INTERVAL '1 DAY'\n    FROM last_three_months\n    WHERE day < CURRENT_DATE AND day > (SELECT DATE(MIN(time_created)) FROM events_raw)\n),\n\ndeployments_per_day AS (\n    SELECT DATE(time_created) AS deploy_day, COUNT(DISTINCT deploy_id) AS daily_deploys\n    FROM deployments\n    GROUP BY deploy_day\n),\n\ndeployments_per_week AS (\n    SELECT EXTRACT(WEEK FROM last_three_months.day)::INT AS week, \n           SUM(daily_deploys) > 0 AS week_deployed, \n           COUNT(DISTINCT last_three_months.day) AS days_deployed\n    FROM last_three_months\n    LEFT JOIN deployments_per_day ON deployments_per_day.deploy_day = last_three_months.day\n    GROUP BY week\n),\n\nmedian_calc AS (\n    SELECT days_deployed, \n           CASE WHEN week_deployed THEN 1 ELSE 0 END AS week_deployed_int,\n           ROW_NUMBER() OVER (ORDER BY days_deployed) AS rn_days,\n           ROW_NUMBER() OVER (ORDER BY CASE WHEN week_deployed THEN 1 ELSE 0 END) AS rn_weeks,\n           COUNT(*) OVER () AS cnt\n    FROM deployments_per_week\n)\n\nSELECT\n    CASE \n        WHEN AVG(days_deployed) FILTER (WHERE rn_days BETWEEN cnt/2 AND cnt/2 + 1) >= 3 THEN 'Daily'\n        WHEN AVG(week_deployed_int) FILTER (WHERE rn_weeks BETWEEN cnt/2 AND cnt/2 + 1) >= 1 THEN 'Weekly'\n        ELSE 'Yearly'\n    END AS deployment_frequency\nFROM median_calc\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Daily Median Time to Restore Services",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "WITH incidents_sorted AS (\n    SELECT \n        time_created::DATE AS day,\n        EXTRACT(EPOCH FROM (time_resolved - time_created))/3600 AS hours_to_restore,\n        ROW_NUMBER() OVER (PARTITION BY time_created::DATE ORDER BY EXTRACT(EPOCH FROM (time_resolved - time_created))/3600) AS rn_asc,\n        ROW_NUMBER() OVER (PARTITION BY time_created::DATE ORDER BY EXTRACT(EPOCH FROM (time_resolved - time_created))/3600 DESC) AS rn_desc,\n        COUNT(*) OVER (PARTITION BY time_created::DATE) AS cnt\n    FROM incidents\n    WHERE time_resolved IS NOT NULL\n),\n\nmedians AS (\n    SELECT \n        day,\n        hours_to_restore,\n        rn_asc,\n        rn_desc,\n        cnt,\n        CASE \n            WHEN cnt % 2 = 1 THEN \n                AVG(hours_to_restore) FILTER (WHERE rn_asc = rn_desc) OVER (PARTITION BY day)\n            ELSE \n                AVG(hours_to_restore) FILTER (WHERE rn_asc IN (rn_desc, rn_desc - 1)) OVER (PARTITION BY day)\n        END AS median_value\n    FROM incidents_sorted\n)\n\nSELECT \n    day AS time,\n    AVG(median_value) AS daily_med_time_to_restore\nFROM medians\nGROUP BY day\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Median Time to Restore Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "WITH incidents_sorted AS (\n    SELECT \n        EXTRACT(EPOCH FROM (time_resolved - time_created))/3600 AS hours_to_resolve,\n        ROW_NUMBER() OVER (ORDER BY EXTRACT(EPOCH FROM (time_resolved - time_created))/3600) AS rn_asc,\n        ROW_NUMBER() OVER (ORDER BY EXTRACT(EPOCH FROM (time_resolved - time_created))/3600 DESC) AS rn_desc,\n        COUNT(*) OVER () AS cnt\n    FROM incidents\n    WHERE time_resolved IS NOT NULL\n    AND time_created > CURRENT_DATE - INTERVAL '3 MONTH'\n)\n\n, medians AS (\n    SELECT \n        hours_to_resolve,\n        rn_asc,\n        rn_desc,\n        cnt,\n        CASE \n            WHEN cnt % 2 = 1 THEN \n                AVG(hours_to_resolve) FILTER (WHERE rn_asc = rn_desc) OVER ()\n            ELSE \n                AVG(hours_to_resolve) FILTER (WHERE rn_asc IN (rn_desc, rn_desc - 1)) OVER ()\n        END AS median_value\n    FROM incidents_sorted\n)\n\n, median_calc AS (\n    SELECT \n        AVG(median_value) AS med_time_to_resolve\n    FROM medians\n)\n\nSELECT \n    CASE \n        WHEN med_time_to_resolve < 24 THEN 'One day'\n        WHEN med_time_to_resolve < 168 THEN 'One week'\n        WHEN med_time_to_resolve < 730 THEN 'One month'\n        WHEN med_time_to_resolve < 730 * 6 THEN 'Six months'\n        ELSE 'One year'\n    END AS med_time_to_restore\nFROM median_calc\nLIMIT 1;\n"
    }
   ]
  },
  {
   "title": "Daily Change Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 10 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\n    DATE(d.time_created) as time,\n    CASE \n        WHEN COUNT(DISTINCT ch.change_id) = 0 THEN 0\n        ELSE \n            SUM(CASE WHEN i.incident_id IS NULL THEN 0 ELSE 1 END)::FLOAT / COUNT(DISTINCT d.deploy_id)\n    END as change_fail_rate\nFROM deployments d\nLEFT JOIN changes ch ON d.main_commit = ch.change_id\nLEFT JOIN incidents i ON ch.change_id = (i.changes[1])\nGROUP BY time\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "WITH subquery AS (\n    SELECT\n        CASE \n            WHEN COUNT(DISTINCT ch.change_id) = 0 THEN 0\n            ELSE \n                SUM(CASE WHEN i.incident_id IS NULL THEN 0 ELSE 1 END)::FLOAT / COUNT(DISTINCT d.deploy_id)\n        END as change_fail_rate\n    FROM deployments d\n    LEFT JOIN changes ch ON d.main_commit = ch.change_id\n    LEFT JOIN incidents i ON ch.change_id = (i.changes[1])\n    WHERE d.time_created > CURRENT_DATE - INTERVAL '3 MONTH'\n)\n\nSELECT\n    CASE \n        WHEN change_fail_rate <= 0.15 THEN '0-15%'\n        WHEN change_fail_rate < 0.46 THEN '16-45%'\n        ELSE '46-60%' \n    END AS change_fail_rate\nFROM subquery\nLIMIT 1;\n"
    }
   ]
  }
 ]
}