apiVersion: apps/v1
kind: Deployment
metadata:
  name: fk-gitlab-parser
  namespace: fourkeys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fk-gitlab-parser
  template:
    metadata:
      labels:
        app: fk-gitlab-parser
    spec:
      containers:
      - name: fk-gitlab-parser
        imagePullPolicy: Never
        image: fleetingclarity/fourkeys/workers/gitlab-parser:main
        env:
        - name: FK_BROKER_ADDRESS
          value: rabbit.fourkeys.svc.cluster.local
        - name: FK_DB_HOST
          value: db.fourkeys.svc.cluster.local
        - name: FK_DB_PW
          value: fourkeys
        - name: FK_DB_USER
          value: fourkeys
