apiVersion: v1
kind: Service
metadata:
  name: rabbit
  namespace: fourkeys
spec:
  type: ClusterIP
  ports:
  - port: 15672
    targetPort: 15672
    name: management
  - port: 5672
    targetPort: 5672
    name: other
  selector:
    app: rabbit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  namespace: fourkeys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3-management
        ports:
          - containerPort: 15672
            name: management
          - containerPort: 5672
            name: other
        env:
        - name: HOSTNAME
          value: "rmq"
