name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [
          'dashboard',
          'event-handler',
          #'workers/argocd-parser',
          #'workers/circleci-parser',
          'workers/github-parser',
          #'workers/pagerduty-parser',
          #'workers/tekton-parser',
          'workers/gitlab-parser'
        ]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Format dockerfile path
      run: |
        echo "FORMATTED_DOCKER_IMAGE=$(echo '${{ matrix.dockerfile }}' | tr '/' '-')" >> $GITHUB_ENV

    - name: Determine Docker tag
      run: |
        REF_NAME="${GITHUB_REF##*/}" # Extracts either 'main' or the tag name.
        IMAGE_BASE="fleetingclarity/fourkeys"
        IMAGE_NAME="${IMAGE_BASE}-${{ env.FORMATTED_DOCKER_IMAGE }}"
        if [[ "${{ github.event_name }}" == "push" && startsWith(github.ref, 'refs/tags/') ]]; then
          echo "DOCKER_TAGS=${IMAGE_NAME}:${REF_NAME},${IMAGE_NAME}:latest" >> $GITHUB_ENV
        else
          echo "DOCKER_TAGS=${IMAGE_NAME}:${REF_NAME}" >> $GITHUB_ENV
        fi


    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ${{ matrix.dockerfile }}
        file: ${{ matrix.dockerfile }}/Dockerfile
        push: true
        tags: ${{ env.DOCKER_TAGS }}
