name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [
          'dashboard',
          'event-handler',
          #'workers/argocd-parser',
          #'workers/circleci-parser',
          'workers/github-parser',
          #'workers/pagerduty-parser',
          #'workers/tekton-parser',
          'workers/gitlab-parser'
        ]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Determine Docker tag
      run: |
        REF_NAME="${GITHUB_REF##*/}" # Extracts either 'main' or the tag name.
        IMAGE_NAME="fleetingclarity/fourkeys/${{ matrix.dockerfile }}"
        if [[ "${{ github.event_name }}" == "push" && "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
          echo "DOCKER_TAGS=${IMAGE_NAME}:${REF_NAME},${IMAGE_NAME}:latest" >> $GITHUB_ENV
        else
          echo "DOCKER_TAGS=${IMAGE_NAME}:${REF_NAME}" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.dockerfile }}
        file: ${{ matrix.dockerfile }}/Dockerfile
        push: true
        tags: ${{ env.DOCKER_TAGS }}
